placeTW/discord-bot

commands/fetch_entry/fetch_entry_main.py
commands/fetch_entry/fetch_entry_ui.py
commands/hgs.py

In particular:
* `ui-fetch` disables everything and edits the message
* `hgs` deletes the message entirely
* `hgs` timeout is now 60 seconds
Also: `ui-fetch` and `fetch` results are now ephemeral

UIs delete/disabled themselves on timeout

---

commands/one_o_one/one_o_one.py
tests/test_one_o_one.py

add tests and fix unwanted \n

---

commands/restart/restart.py
main.py

feat: restart command

---

main.py

Registers these commands in other servers:
- 101
- hgs
- doge
- gothefucktosleep
- capoo
To take advantage of this functionality, the `DISCORD_GUILD` environment variable should be converted to a string separating each discord server with a comma. The first ID in the list is assumed to be the placeTW discord server ID.

feat: register slash commands in other servers

---

commands/confessions/confession.py
main.py

add confession functionality

---

.gitignore
commands/confessions/confession.py
main.py
utils.py

Changed how guild info is read (to a json file) alongside identifying the correct guild in `confessions.py`

Guilds env

---

.gitignore
commands/tocfl/consts.py
commands/tocfl/tocfl.py
main.py

Current functionalities:
* `random`: selects a random word, optionally with level.

TOCFL words

---

commands/bbt_count/bbt_count.py
commands/bbt_count/consts.py
commands/bbt_count/embeds.py
commands/bbt_count/helpers.py
tests/test_bbt_count/test_helpers.py

Option to group bubble tea entries by location or currency in the `bbt_count list` command

feat: group_by parameter for `bbt_count list`

---

commands/react_earthquake/react_earthquake.py
main.py

feat: earthquake

---

.github/workflows/run_test.yml

* Use Poetry instead of pip (`requirements.txt`)
* Try using Poetry caching (not sure if it works)
* Only run tests when *.py or this actions file is modified

Have GitHub Actions switch to using Poetry

---

commands/taiwanese/taiwanese_entry.py

* Added resources for Taiwanese pronunciation
* Preprocess POJ to prevent broken markdown

Taigi: Pronunciation resources and POJ preprocessing

---

commands/taiwanese/quiz.py
commands/taiwanese/read_embree_csv.py
commands/taiwanese/taiwanese_entry.py
modules/quiz/multiple_choice.py

* Created general purpose quiz module
* Used general purpose quiz module to create quiz for Taigi (based on Embree database)

Generic Quiz module and Taigi Quiz

---

.github/workflows/run_test.yml
commands/taiwanese/read_embree_csv.py
tests/test_taigi.py

* Created tests
* Found and added test cases for strings that are problematic but will be ignored for now
* Fixed bugs in code based on tests
* removed `-v`
* added `--durations=5` which shows the 5 slowest tests

Test taigi + other test changes

---

commands/tocfl/chewing.py
commands/tocfl/tocfl.py

- Added Zhuyin to the `/tocfl` embed

Add Zhuyin

---

commands/tocfl/chewing.py
commands/tocfl/db.py
commands/tocfl/quiz.py
commands/tocfl/tocfl.py

```
Choose the correct answer for: 自私
Choices:
* dòng / ㄉㄨㄥˋ
* zìsī / ㄗˋ ㄙ¯
* xiānnăi / ㄒㄧㄢ¯ ㄋㄞˇ
* zuìjiā / ㄗㄨㄟˋ ㄐㄧㄚ¯
```
and
```
Choose the correct answer for: cìhòu / ㄘˋ ㄏㄡˋ 
Choices:
* 派出所
* 連結
* 伺候
* 本子
```

Tocfl quiz

---

.gitignore
resources/reacts/czech.json
tests/test_reacts/test_reacts_cz.py

Add Mandarin word for Czechia to Czech reacts

---

commands/tocfl/quiz_bopomofo.py
commands/tocfl/quiz_vocab.py
commands/tocfl/tocfl.py
modules/quiz/multiple_choice.py

Quiz but for bopomofo-pinyin
* `/tocfl quiz-zhuyin`
* `/tocfl quiz-bopofomo`

Zhuyin quiz

---

commands/cat/cat.py
main.py
modules/async_utils.py

Adds cat api
Requires `CAT_API_KEY` in the `.env` file from https://thecatapi.com/

feat: cat api

---

commands/compare/compare.py
commands/compare/compare_api.py
commands/compare/compare_cmd.py
commands/compare/consts.py
main.py
modules/async_utils.py

Current implementation: `/compare cities` which takes two cities from a list of choices. Also provides the source (link to the website) as requested.
Could probably ask the user to prompt their own cities in the future but that requires more error handling

Compare prices command

---

commands/trains/consts.py
commands/trains/trains.py
main.py

- Refactor references of "metro" to "trains"
- Add THSR Map

Refactor trains command + THSR
